### ISSUE TITLE
COVID-19 R resources

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [LucyMcGowan/teaching-in-coronavirus-era#1]
I've been collecting (mostly) R related COVID-19 resources at https://github.com/mine-cetinkaya-rundel/covid19-r. Those teaching R might find some of the entries here useful, so feel free to include if it fits with the rest of the resources. Thanks for putting this together!

**Comment by LucyMcGowan** [comment]
Thank you Mine! I added it here (#2) let me know if you'd like the text changed
